#!/usr/bin/python

import subprocess
import os
from get import mkdir, symlink
from globals import REPO_DIR, REPO_FLAT_DIR

mkdir(REPO_FLAT_DIR)
repos = subprocess.run(["starfarm_find_git_repos " + REPO_DIR], capture_output=True, shell=True, cwd=os.getcwd()).stdout.decode('utf-8').strip().split("\n")
for repo in repos:
    relpath = os.path.relpath(repo, REPO_DIR).replace("/", "_")
    dest = os.path.join(REPO_FLAT_DIR, relpath)
    symlink(repo, dest)
