#!/usr/bin/python
# manual helper functions that aren't used in the main program to help clean the repo library
# exit()


def clean_failed_asterix_stars(): 
    # oops, when creating the asterisk tags.yaml feature/option, the repos were actually starred - this unstars them
    from farm import Farm
    farm = Farm()
    tags_file = farm._load_yaml_file("tags.yaml") 
    for tag in tags_file:
        if "*" in tag:
            for full_name in tags_file[tag]:
                if full_name is not None:
                    owner_name = full_name.split("/")
                    farm.unstar({ 'owner' : owner_name[0], 'name': owner_name[1] })
    

# change all repos to lowercase
def all_repos_to_lowercase():
    import os
    from globals import STARFARM_DIR
    os.chdir(STARFARM_DIR)
    for owner in os.listdir(STARFARM_DIR):
        sub = os.path.join(STARFARM_DIR, owner)
        if os.path.isdir(sub):
            os.rename(owner, owner.lower())


# all_repos_to_lowercase()

clean_failed_asterix_stars()
