#!/usr/bin/python
# this script will never unstar repos
from get import *
import time, multiprocessing, shutil
from globals import home, SCRIPT_DIR, PLUGIN_DIR, REPO_DIR, STARFARM_DIR, REPO_TAG_DIR, REPO_FLAT_DIR
# start = time.perf_counter()


# print(api.rate_limit.get())

print("Retrieving stars from github...")
# get_stars
manager = multiprocessing.Manager()
stars = manager.list()
p = multiprocessing.Process(target=get_stars, args=([stars]))
p.start()

packer = get_packer()
fs = get_fs()
syms = get_syms()
config = get_config()
unsorted = get_unsorted()

# print(f"Completed Getting Data in {time.perf_counter() - start} seconds")

for dir in [REPO_DIR, STARFARM_DIR, REPO_TAG_DIR, REPO_FLAT_DIR]:
    mkdir(dir)




# wait to get stars
p.join()
# print(f"Get Stars done in {time.perf_counter() - start} seconds")
stars_nopacker = filter_by_fullname(stars, packer)
stars_nopacker_nofs = filter_by_fullname(stars_nopacker, fs)





# REPOS


# find repos I have starred, downloaded, then unstarred
repos_to_clean = filter_by_fullname(fs, stars_nopacker)
print(steps(1) + "for fs not in stars - remove...")
for repo in repos_to_clean:
    dest = os.path.join(STARFARM_DIR, repo["full_name"])
    print("- Removing Repo from fs: " + dest)
    shutil.rmtree(dest)


# then download the rest
print(steps(2) + "for stars not in fs - clone..")
if len(stars_nopacker_nofs) > 0:
    clone_all(stars_nopacker_nofs)

print(steps(3) + "for config not in fs - clone...")
config_nofs = filter_by_fullname(filter_by_fullname(config, packer), fs)
for repo in config_nofs:
    clone(repo)

print(steps(4) + "for stars not in config - modify tags_unsorted.yaml...")
stars_noconfig = filter_by_fullname(stars, config)
# find the difference only to print new
stars_noconfig_nounsorted = filter_by_fullname(stars_noconfig, unsorted)
unsorted_nostars = filter_by_fullname(unsorted, stars)
for repo in unsorted_nostars:
    print("- tags_unsorted: " + repo["full_name"])

for repo in stars_noconfig_nounsorted:
    print("+ tags_unsorted: " + repo["full_name"])

# write all the results again instead of appending
with open(os.path.join(SCRIPT_DIR, 'tags_unsorted.yaml'), 'w') as file:
    yaml.dump([repo["full_name"] for repo in stars_noconfig], file)


# at this point, the fs and unsorted have been modified, and all repos have been downloaded
all_repos = get_all_repos()
unsorted = get_unsorted()
fs = get_fs()
syms_to_create = filter_by_fullname_tag(config + unsorted, syms)
syms_to_remove = filter_by_fullname_tag(syms, config + unsorted)


#  SYMLINKS 
print(steps(5) + "for tag syms not in config - remove syms")
for repo in syms_to_remove:
    owner_name = repo["owner"] + "|" + repo["name"]
    target = os.path.join(REPO_TAG_DIR, repo["tag"], owner_name)
    os.remove(target)
    print("- Removing symlink: " + target)

print(steps(6) + "for config not in tag syms - create syms...")
for repo in syms_to_create:
    mkdir(os.path.join(REPO_TAG_DIR, repo["tag"]))
    source = find_repo_source(all_repos, repo)
    dest = os.path.join(REPO_TAG_DIR, repo["tag"], repo["full_name"].replace("/", "|"))
    os.symlink(source, dest)
    print("+ " + source + " --> " + dest)



print(steps(7) + "for config not in stars - starring...")
 
config_nostars = filter_by_fullname(config, stars)
for repo in config_nostars:
    if repo["star"]:
        star(repo)

print(steps(8) + "for packer not in stars - starring...")
packer_nostars = filter_by_fullname(packer, stars)
for plugin in packer_nostars:
    star(plugin)


print(steps(9) + "removing empty folders...")
remove_empty_folders(STARFARM_DIR)
remove_empty_folders(REPO_TAG_DIR)

# symlink new repos into REPO_FLAT_DIR
flat_repos = get_flat_repos()
print("for all repos not in flat syms: -- create syms.. ")
all_noflat = filter_by_fullname(all_repos, flat_repos)
for repo in all_noflat:
    print(repo)
    filename = "|".join([repo["cat"], repo["owner"], repo["name"]])
    source = repo["abs"]
    dest = os.path.join(REPO_FLAT_DIR, filename)
    os.symlink(source, dest)



print("for flat syms not in all repos - remove syms...")
flat_noall = filter_by_fullname(flat_repos, all_repos)
## REMOVE SYMS.. MAKE SUR
for repo in flat_noall:
    abs = os.path.join(REPO_FLAT_DIR, repo["filename"])
    print("Removing: " + abs)
    os.remove(abs)
